<?php
/**
 * @file Fire Badges: Client-side badging system.
 */

/**
 * Implements hook_menu().
 */
function firebadges_menu() {
  return array(
    'admin/config/services/firebadges' => array(
      'title' => 'Fire Badges',
      'description' => 'Client-side badging system.',
      'type' => MENU_CALLBACK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('firebadges_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'firebadges.admin.inc',
    ),
  );
}

/**
 * Implements hook_library().
 */
function firebadges_library() {
  // Allow local symlink development.
  $path = variable_get('firebadges_library', FALSE) ?: libraries_get_path('deft');

  return array(
    'deft' => array(
      'title' => 'Deft: client-side badges',
      'version' => '0.1.0',
      'js' => array(
        $path . '/deft.js' => array(
          'type' => 'file',
          'group' => JS_LIBRARY,
        ),
      ),
      'css' => array(
        $path . '/deft.css' => array(
          'type' => 'file',
          'media' => 'screen',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function firebadges_page_build(&$page) {
  global $user;
  $active_roles = array_filter(variable_get('firebadges_roles', array()));
  $active = variable_get('firebadges_toggle', TRUE) &&
      variable_get('firebadges_firebase_url', '') &&
      array_intersect_key($active_roles, $user->roles);

  if ($active) {
    // Assets and settings.
    drupal_add_library('firebadges', 'deft');
    drupal_add_js(drupal_get_path('module', 'firebadges') . '/firebadges.js');
    drupal_add_js(array('fireBadges' => array(
      'firebaseUrl' => variable_get('firebadges_firebase_url', ''),
    )), 'setting');
  }
}
