<?php
/**
 * @file Fire Badges: Client-side badging system.
 */

/**
 * Implements hook_menu().
 */
function firebadges_menu() {
  return array(
    'admin/config/services/firebadges' => array(
      'title' => 'Fire Badges',
      'description' => 'Client-side badging system.',
      'type' => MENU_CALLBACK,
      'page callback' => 'drupal_get_form',
      'access arguments' => array('access administration pages'),
      'file' => 'firebadges.admin.inc',
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function firebadges_page_build(&$page) {
  global $user;
  $active = variable_get('firebadges_toggle', FALSE) &&
      variable_get('firebadges_public_key', '') &&
      variable_get('firebadges_private_key', '') &&
      in_array(variable_get('firebadges_roles', array()), $user->roles);
  if (!$active) {
    return false;
  }

  // Allow local symlink development.
  $path = variable_get('firebadges_library', FALSE) ?: 'deft/deft.js';

  // Add assets.
  drupal_add_js(drupal_get_path('module', 'firebadges') . '/' . $path);
  drupal_add_js(array('fireBadges' => array(
    'publicKey' => variable_get('firebadges_public_key', ''),
    'privateKey' => variable_get('firebadges_private_key', '')
  )), 'setting');
}
